name: Employeefrontend DevSecOps Workflow

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  sonarcloud-scan:
    runs-on: ubuntu-latest
    steps:
      - name: Step1 Download the Source code
        uses: actions/checkout@v3.5.3

      - name: Step2 Install Node.js
        uses: actions/setup-node@v3.7.0
        with:
          node-version: '18.16.1'

      - name: Step3 Install Dependencies
        run: npm install
      
      - name: Step4 SonarCloud Scan
        uses: sonarsource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Needed to get PR information, if any
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        with:
          args: >
             -Dsonar.organization=employeefrontend-fursan-track3
             -Dsonar.projectKey=employeefrontend-fursan-track3_employeefrontend-fursan-track3
             -Dsonar.sources=.
             -Dsonar.host.url=https://sonarcloud.io